allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

subprojects { project ->
    project.plugins.whenPluginAdded { plugin ->
        def isAppPlugin = plugin.class.name.contains('com.android.build.gradle.AppPlugin')
        def isLibraryPlugin = plugin.class.name.contains('com.android.build.gradle.LibraryPlugin')
        
        if (isAppPlugin || isLibraryPlugin) {
            project.android {
                compileSdk 36
                if (isAppPlugin) {
                    targetSdk 36
                }
                if (project.name == 'isar_flutter_libs') {
                    namespace 'com.isar.isar_flutter_libs'
                }
            }
        }
    }
}